mysql_master:
  image: jaka/mysql
  environment:
    MYSQL_USER: 'admin'
    MYSQL_PASS: 'mypass'
    REPLICATION_MASTER: 'true'
    REPLICATION_USER: 'replica'
    REPLICATION_PASS: 'replica'
  ports:
    - '3306:3306'

mysql_slave_1:
  image: jaka/mysql
  environment:
    MYSQL_PASS: 'mypass'
    REPLICATION_SLAVE: 'true'
    REPLICATION_USER: 'replica'          
    REPLICATION_PASS: 'replica'
  ports:
    - '3307:3306'
  links:
    - mysql_master:mysql

mysql_slave_2:
  image: jaka/mysql
  environment:
    MYSQL_PASS: 'mypass'
    REPLICATION_SLAVE: 'true'
    REPLICATION_USER: 'replica'          
    REPLICATION_PASS: 'replica'
  ports:
    - '3308:3306'
  links:
    - mysql_master:mysql
